### ISSUE TITLE
chapter.5_1 BugCheck 0x50

### ISSUE THREAD

**Issue by imdudu1** [greemate/windbgwindbg2nd#1]
5.1 챕터에서 BugCheck 0x50을 사용하는데 다운받은 예제에서 5_1에는 0x50이 포함이 안되어있고 5_3에 2가지의 BugCheck 0x50이 포함되어 있는데 의도된 구성인지 궁금하여 남깁니다.

**Comment by greemate** [comment]
네. 의도한 구성이 맞습니다. 5.1 챕터의 BugCheck 0x50 설명은 저자들의 업무 현장에서 나온 실전 예제를 각색한 내용입니다. 따라서 덤프파일을 제공해 드리지 못 하는 점 양해 부탁드리겠습니다. 덤프파일 제공이 없는 설명들은 이와 같은 상황이라는 점을 기억해 주시면 감사하겠습니다. ^^
